### PR TITLE
[Need Help] Why is ast.Call node having strange error?

### PR DESCRIPTION
**Pull request by MarisaKirisame**
So I am testing the water on adding new AST cases, by modifying UnaryOp to UnaryOpC, a supposedly equivalent class.
However, Call start to give error, while it has nothing to do with UnaryOp!
I think it might be caused by Call having UnaryOpC inside, but I'm not certain, any idea?

### CODE REVIEW

**Comment by thautwarm** [comment]
When making an extended AST, we should set `_fields` manually.

https://github.com/Xython/YAPyPy/blob/85c9d254bef3a7bf2b7af0590a554195377e50c5/yapypy/extended_python/extended_ast.py#L24

**Comment by thautwarm** [comment]
@lfkdsk

**Comment by lfkdsk** [comment]
got it!
maybe we could append it to the doc and make it better.

**Comment by thautwarm** [comment]
well, to be finished tonight.

**Comment by lfkdsk** [comment]
But why we don't split origin AST and extended AST into two emit point?

**Pull request closed without merging**
