### PR TITLE
use good old Visitor pattern, instead of Redy magic

### PR DESCRIPTION
**Pull request by demarcator**

### CODE REVIEW

**Comment by thautwarm** [comment]
`method = 'visit_' + node.__class__.__name__` is evil, please.  
`Redy.Magic.Pattern` is driven through table, `Redy.Tools.Path` could automatically resolve the path/encoding for windows and some linux distributions.

**Comment by demarcator** [comment]
In Python 3, source files should be encoded in UTF-8, otherwise they should follow PEP-263.

**Comment by demarcator** [comment]
`ast.NodeVisitor` did the same, you already have kizmi poisoned.

**Comment by thautwarm** [comment]
dbg-script might not use utf-8 encoding, and no one says we just deal with python source code files.

**Comment by thautwarm** [comment]
`ast.NodeVisitor` uses type name to do dynamic dispatch.

**Comment by demarcator** [comment]
`method = 'visit_' + node.__class__.__name__` is copied from `ast.NodeVisitor`

**Comment by thautwarm** [comment]
I known that and exactly it's what I disagree with.

**Comment by demarcator** [comment]
I don't think `stream.read(1)` is very helpful in detecting encoding.

**Comment by demarcator** [comment]
https://github.com/thautwarm/kizmi/blob/7aa5d01dd4f3de9011de250ffe8e677f078a884e/kizmi/extended_python/helper.py#L8

**Comment by thautwarm** [comment]
it works, I've tried.

**Comment by demarcator** [comment]
https://chardet.readthedocs.io/en/latest/faq.html#isnt-that-impossible

**Comment by thautwarm** [comment]
I use those old visitors to manipulate standard python asts so I don't need to make a big new one.

**Comment by thautwarm** [comment]
I didn't use chardet but I used to. When I tried it with `read(1024)`, the result is not correct so I use the simple traversing on common encodings.

**Pull request closed without merging**
